#gazebo_ros_control:
#  pid_gains:
#    arm_shoulder_pan_joint:   {p: 0.0, i: 0.0, d: 0.01}
#    arm_shoulder_lift_joint:   {p: 0.0, i: 0.0, d: 0.01}
#    arm_elbow_joint:   {p: 0.0, i: 0.0, d: 0.01}
#    arm_wrist_1_joint:   {p: 0.0, i: 0.0, d: 0.01}
#    arm_wrist_2_joint:  {p: 0.0, i: 0.0, d: 0.01}
#    arm_wrist_3_joint:   {p: 0.0, i: 0.0, d: 0.01}


   
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - arm_shoulder_pan_joint
     - arm_shoulder_lift_joint
     - arm_elbow_joint
     - arm_wrist_1_joint
     - arm_wrist_2_joint
     - arm_wrist_3_joint
  
#  gains: # Required because we're controlling a velocity interface
#    arm_shoulder_pan_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
#    arm_shoulder_lift_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
#    arm_elbow_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
#    arm_wrist_1_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
#    arm_wrist_2_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
#    arm_wrist_3_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - arm_shoulder_pan_joint
     - arm_shoulder_lift_joint
     - arm_elbow_joint
     - arm_wrist_1_joint
     - arm_wrist_2_joint
     - arm_wrist_3_joint